- platform: qnap
  host: !secret qnap_host
  username: !secret qnap_user
  password: !secret qnap_password
  port: 443
  ssl: true
  verify_ssl: false
  monitored_conditions:
    - status
    - system_temp
    - cpu_usage
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - volume_size_used
  volumes:
    - DataVol1
